---
#
# Playbook to install node-exporter and run cadvisor docker
#

- hosts: instances
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  roles:
    #- { role: update }
    - { role: node_exporter }
    #  - { role: cadvisor }
